### ISSUE TITLE
能否添加又拍云上传功能

### ISSUE THREAD

**Issue by leveychen** [benqy/hexomd#1]
Rt。 感谢作者分享~

**Comment by leveychen** [comment]
东西挺好用，说两个问题，
一个是能否双栏，左栏编写MD代码，右栏预览，最好能实时预览，（21:9）的显示器，请理解。。
还有一个是，底部弹出菜单设置完成之后不会自动缩回，必须点击对应菜单。
最后就是，又拍云才是王道。。求添加。

**Comment by benqy** [comment]
好,我看看.谢谢反馈!

**Comment by benqy** [comment]
已更新0.10.0.0版
1. 预览窗口现在可在设置里选择双栏或者新窗口打开
2. 故意做成不自动缩回的,因为这样在选择样式的时候不用频繁的点击按钮.
3. 今天已经把文件上传的代码独立出来了,有空的时候会增加又拍云的支持

**Comment by benqy** [comment]
又拍云试用还要绑定支付宝啊..我看错了么,暂时不加了
