### ISSUE TITLE
是否有创建Electron版本的计划？

### ISSUE THREAD

**Issue by dusdong** [benqy/hexomd#2]
感谢您开源的hexom及系列文章，又看到了您有写Electron框架的文章，不知道是否有将此项目创建Electron版本的计划？看起来Electron更具发展潜力。谢谢

**Comment by benqy** [comment]
一直没去看electron,换成它的话,有什么优点么.
这几天有时间看看electron

**Comment by dusdong** [comment]
官方有个简单的对比：https://github.com/atom/electron/blob/master/docs-translations/zh-CN/development/atom-shell-vs-node-webkit.md

从网上的评论看，Electron貌似更有对比优势：https://www.zhihu.com/question/38854224

Electron的资源列表：https://github.com/sindresorhus/awesome-electron

**Comment by benqy** [comment]
看了下,是比nw好,但是对于我这个项目,用这两个都差不多.切换并不能带来多大的好处,代价有点大.  现在还是把时间花在完善功能和体验上.
有兴趣的话,可以建个分支去做electron版

**Comment by dusdong** [comment]
我刚开始学Electron，对于建分支，我还得攒攒能力值先

**Comment by benqy** [comment]
可以做点小东西.我最近需要做个内部工具,考虑用electron.
