### ISSUE TITLE
如何在Linux下运行？

### ISSUE THREAD

**Issue by izuolan** [benqy/hexomd#3]
我在Linux下运行后界面有些崩，而且只能看不能用。。。。可以讲一下大概需要怎么做吗？

**Comment by benqy** [comment]
不好意思..我目前只对window做兼容,没想到还有linux用户:smile:
linux下应该是一些node包要重新安装一下,还有可能就是路径问题.
我看看,这周末解决

**Comment by izuolan** [comment]
万分感谢！！～～

**Comment by izuolan** [comment]
真是抱歉，我又回来了，实在找不到好用的。。。。笑

**Comment by benqy** [comment]
实在是抱歉啊..在linux下错误有点多,一时半会我弄不好,公司项目最近比较忙,这个东西都没怎么维护.不知道什么时候才能弄好

**Comment by izuolan** [comment]
没关系，那我先关了issue～～
